import type { ThemeDefinition } from './types';

export const DARK: ThemeDefinition = {
  id: 'builtin-dark',
  name: 'Dark',
  builtin: true,
  tokens: {
    'sh3-bg':            '#1a1b1e',
    'sh3-bg-elevated':   '#22232a',
    'sh3-bg-sunken':     '#141518',
    'sh3-input-bg':      '#2a2a2a',
    'sh3-border':        '#2e3038',
    'sh3-border-strong': '#3c3f4a',
    'sh3-fg':            '#e4e6eb',
    'sh3-fg-muted':      '#9aa0aa',
    'sh3-fg-subtle':     '#6b7280',
    'sh3-accent':        '#6ea8fe',
    'sh3-accent-muted':  '#3a5580',
    'sh3-error':         '#f87171',
    'sh3-warning':       '#fbbf24',
    'sh3-success':       '#34d399',
    'sh3-fg-on-accent':  '#1a1b1e',
    'sh3-fg-on-error':   '#1a1b1e',
    'sh3-fg-on-warning': '#1a1b1e',
    'sh3-fg-on-success': '#1a1b1e',
    'sh3-radius-sm':     '3px',
    'sh3-radius':        '4px',
    'sh3-radius-md':     '6px',
    'sh3-radius-lg':     '8px',
    'sh3-font-ui':       'system-ui, -apple-system, "Segoe UI", sans-serif',
    'sh3-font-mono':     'ui-monospace, "Cascadia Code", "Consolas", monospace',
    'sh3-font-size':     '13px',
    'sh3-line':          '1.45',
  },
};

export const LIGHT: ThemeDefinition = {
  id: 'builtin-light',
  name: 'Light',
  builtin: true,
  tokens: {
    'sh3-bg':            '#f5f5f7',
    'sh3-bg-elevated':   '#ffffff',
    'sh3-bg-sunken':     '#e8e8ed',
    'sh3-input-bg':      '#e8e8ed',
    'sh3-border':        '#d2d2d7',
    'sh3-border-strong': '#b8b8bf',
    'sh3-fg':            '#1d1d1f',
    'sh3-fg-muted':      '#6e6e73',
    'sh3-fg-subtle':     '#86868b',
    'sh3-accent':        '#0066cc',
    'sh3-accent-muted':  '#99c4e8',
    'sh3-error':         '#dc2626',
    'sh3-warning':       '#d97706',
    'sh3-success':       '#16a34a',
    // Driven via Algorithm A; fg-on-error overridden to #ffffff because
    // driven #f5f5f7 only reaches 4.44 (fails AA) while #ffffff hits 4.83.
    'sh3-fg-on-accent':  '#f5f5f7',
    'sh3-fg-on-error':   '#ffffff',
    'sh3-fg-on-warning': '#1d1d1f',
    'sh3-fg-on-success': '#1d1d1f',
    'sh3-radius-sm':     '4px',
    'sh3-radius':        '6px',
    'sh3-radius-md':     '8px',
    'sh3-radius-lg':     '10px',
    'sh3-font-ui':       'system-ui, -apple-system, "Segoe UI", sans-serif',
    'sh3-font-mono':     'ui-monospace, "Cascadia Code", "Consolas", monospace',
    'sh3-font-size':     '13px',
    'sh3-line':          '1.45',
  },
};

export const NEON_PULSE: ThemeDefinition = {
  id: 'builtin-neon-pulse',
  name: 'Neon Pulse',
  builtin: true,
  tokens: {
    'sh3-bg':            '#0d0b1a',
    'sh3-bg-elevated':   '#1a1035',
    'sh3-bg-sunken':     '#080610',
    'sh3-input-bg':      '#241a40',
    'sh3-border':        '#6c3bff33',
    'sh3-border-strong': '#6c3bff55',
    'sh3-fg':            '#e8e0ff',
    'sh3-fg-muted':      '#8877aa',
    'sh3-fg-subtle':     '#554466',
    'sh3-accent':        '#bf7aff',
    'sh3-accent-muted':  '#6c3bff',
    'sh3-error':         '#ff6b8a',
    'sh3-warning':       '#ffb86c',
    'sh3-success':       '#50fa7b',
    'sh3-fg-on-accent':  '#0d0b1a',
    'sh3-fg-on-error':   '#0d0b1a',
    'sh3-fg-on-warning': '#0d0b1a',
    'sh3-fg-on-success': '#0d0b1a',
    'sh3-radius-sm':     '2px',
    'sh3-radius':        '3px',
    'sh3-radius-md':     '4px',
    'sh3-radius-lg':     '6px',
    'sh3-font-ui':       'system-ui, -apple-system, "Segoe UI", sans-serif',
    'sh3-font-mono':     'ui-monospace, "Cascadia Code", "Consolas", monospace',
    'sh3-font-size':     '13px',
    'sh3-line':          '1.45',
    'sh3-grad-bg':          'linear-gradient(135deg, #0d0b1a 0%, #1a1035 100%)',
    'sh3-grad-bg-elevated': 'linear-gradient(180deg, #2a1a4a, #1a1035)',
    'sh3-grad-bg-sunken':   'linear-gradient(180deg, #080610, #0d0b1a)',
  },
};

export const JADE_GARDEN: ThemeDefinition = {
  id: 'builtin-jade-garden',
  name: 'Jade Garden',
  builtin: true,
  tokens: {
    'sh3-bg':            '#fafbf9',
    'sh3-bg-elevated':   '#ffffff',
    'sh3-bg-sunken':     '#e8ede4',
    'sh3-input-bg':      '#e8ede4',
    'sh3-border':        '#c8d4c0',
    'sh3-border-strong': '#a8b8a0',
    'sh3-fg':            '#2d3a2e',
    'sh3-fg-muted':      '#5a6a58',
    'sh3-fg-subtle':     '#7a8a72',
    'sh3-accent':        '#5a8a5e',
    'sh3-accent-muted':  '#a0c8a2',
    'sh3-error':         '#c0392b',
    'sh3-warning':       '#b8860b',
    'sh3-success':       '#2e7d32',
    // Algorithm A gave sub-AA values for accent (3.87) and warning (3.67)
    // against this preset's own light fg/bg; overridden to #000000 which
    // reaches 5.23 and 6.45 respectively.
    'sh3-fg-on-accent':  '#000000',
    'sh3-fg-on-error':   '#fafbf9',
    'sh3-fg-on-warning': '#000000',
    'sh3-fg-on-success': '#fafbf9',
    'sh3-radius-sm':     '6px',
    'sh3-radius':        '8px',
    'sh3-radius-md':     '10px',
    'sh3-radius-lg':     '14px',
    'sh3-font-ui':       'Georgia, "Times New Roman", serif',
    'sh3-font-mono':     'ui-monospace, "Cascadia Code", "Consolas", monospace',
    'sh3-font-size':     '13px',
    'sh3-line':          '1.5',
    'sh3-grad-bg':          'linear-gradient(160deg, #fafbf9 0%, #f0f4ec 100%)',
    'sh3-grad-bg-elevated': 'linear-gradient(180deg, #f5f8f2, #eef2ea)',
    'sh3-grad-bg-sunken':   'linear-gradient(90deg, #e8ede4, #eef2ea)',
  },
};

export const MATCHA_INK: ThemeDefinition = {
  id: 'builtin-matcha-ink',
  name: 'Matcha Ink',
  builtin: true,
  tokens: {
    'sh3-bg':            '#1c2420',
    'sh3-bg-elevated':   '#243028',
    'sh3-bg-sunken':     '#161e19',
    'sh3-input-bg':      '#2a3a2e',
    'sh3-border':        '#2d3d30',
    'sh3-border-strong': '#3a4d3e',
    'sh3-fg':            '#c8d8c4',
    'sh3-fg-muted':      '#7a9a78',
    'sh3-fg-subtle':     '#5a7a58',
    'sh3-accent':        '#88c88a',
    'sh3-accent-muted':  '#3a6a3c',
    'sh3-error':         '#e57373',
    'sh3-warning':       '#dce775',
    'sh3-success':       '#81c784',
    'sh3-fg-on-accent':  '#1c2420',
    'sh3-fg-on-error':   '#1c2420',
    'sh3-fg-on-warning': '#1c2420',
    'sh3-fg-on-success': '#1c2420',
    'sh3-radius-sm':     '2px',
    'sh3-radius':        '3px',
    'sh3-radius-md':     '5px',
    'sh3-radius-lg':     '7px',
    'sh3-font-ui':       'system-ui, -apple-system, "Segoe UI", sans-serif',
    'sh3-font-mono':     'ui-monospace, "Cascadia Code", "Consolas", monospace',
    'sh3-font-size':     '13px',
    'sh3-line':          '1.45',
    'sh3-grad-bg':          'linear-gradient(150deg, #1c2420 0%, #202d25 50%, #1a2320 100%)',
    'sh3-grad-bg-elevated': 'linear-gradient(180deg, #243028, #1c2420)',
    'sh3-grad-bg-sunken':   'linear-gradient(90deg, #161e19, #1a241e)',
  },
};

/** All built-in presets, in display order. */
export const BUILTIN_PRESETS: ThemeDefinition[] = [
  DARK, LIGHT, NEON_PULSE, JADE_GARDEN, MATCHA_INK,
];
